config/routes.rb
OpenLists::Engine.routes.draw do
  scope '/:domain/:list_name' do
    get 'define', controller: :generic, action: :define_model
    resources '', controller:  :generic
  end

  #scope '/:domain' do
  #  resources '', controller:  :domain_lists
  #end

  get '', controller:  :domains, action: :index
  get '/:domain', controller: :domains, action: :index, domain: ':domain'

end

app/controllers/open_lists/application_controller.rb
module OpenLists
  class ApplicationController < ActionController::Base
    helper_method :sort_column, :sort_direction

    def sort_column
      @model.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[desc asc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    protected

    def determine_model
      determine_domain
      unless @domain.nil?
        @model ||= @domain.model_class(params[:list_name])
        redirect_to controller: :domain_lists, action: :index unless @model
      end
    end

    def determine_domain
      @domain ||= DynamicModel::ManagedDomains.domain_module params[:domain]
      redirect_to controller: :domains, action: :index unless @domain
    end


  end
end

app/controllers/open_lists/domains_controller.rb
require_dependency "open_lists/application_controller"

module OpenLists
  class DomainsController < ApplicationController

    before_filter :determine_domain

    # GET /domains
    # GET /domains.json
    def index
      @domains = Domain.order(sort_column + " " + sort_direction)

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @domains }
        format.js # index.js.coffee
      end

    end

    # GET /domains/new
    # GET /domains/new.json
    def new
      @domain = Domain.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @domain }
      end
    end
  
    # GET /domains/1/edit
    def edit
      @domain = Domain.find(params[:id])
    end
  
    # POST /domains
    # POST /domains.json
    def create
      @domain = Domain.new(params[:domain])
  
      respond_to do |format|
        if @domain.save
          format.html { redirect_to view_context.domains_path, notice: 'Domain was successfully created.' }
          format.json { render json: @domain, status: :created, location: @domain }
        else
          format.html { render action: "new" }
          format.json { render json: @domain.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /domains/1
    # PUT /domains/1.json
    def update
      @domain = Domain.find(params[:id])
  
      respond_to do |format|
        if @domain.update_attributes(params[:domain])
          format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @domain.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /domains/1
    # DELETE /domains/1.json
    def destroy
      @domain = Domain.find(params[:id])
      @domain.destroy
  
      respond_to do |format|
        format.html { redirect_to domains_url }
        format.json { head :no_content }
      end
    end

    private

    def determine_domain
      @model = OpenLists::Domain
    end

  end
end

app/controllers/open_lists/generic_controller.rb
require_dependency "open_lists/application_controller"

module OpenLists
  class GenericController < ApplicationController
    before_filter :determine_model


    # GET /open_lists/:domain/:list_name
    # GET /open_lists/:domain/:list_name.json
    def index
      @items = @model.order(sort_column + " " + sort_direction).page(params[:page]).per(params[:per])
      if @items.empty? && params[:page]
        params[:page] = nil
        @items = @model.order(sort_column + " " + sort_direction).page(params[:page]).per(params[:per])
      end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @items }
        format.js # index.js.coffee
      end
    end

    # GET /open_lists/:domain/:list_name/1
    # GET /open_lists/:domain/:list_name/1.json
    def show
      @item = @model.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @item }
      end
    end

    # GET /open_lists/:domain/:list_name/new
    # GET /open_lists/:domain/:list_name/new.json
    def new
      @item = @model.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @item }
      end
    end

    # GET /open_lists/:domain/:list_name/1/edit
    def edit
      @item = @model.find(params[:id])
    end

    # POST /open_lists/:domain/:list_name
    # POST /open_lists/:domain/:list_name.json
    def create
      @item = @model.new(params[actual_list_param_name])

      respond_to do |format|
        if @item.save
          format.html { redirect_to view_context.item_path(@item), notice: 'Item was successfully created.' }
          format.json { render json: @item, status: :created, location: @item }
        else
          format.html { render action: "new" }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /open_lists/:domain/:list_name/1
    # PUT /open_lists/:domain/:list_name/1.json
    def update
      @item = @model.find(params[:id])
      respond_to do |format|
        if @item.update_attributes(params[actual_list_param_name])
          format.html { redirect_to view_context.item_path(@item), notice: 'Item was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /open_lists/:domain/:list_name/1
    # DELETE /open_lists/:domain/:list_name/1.json
    def destroy
      @item = @model.find(params[:id])
      @item.destroy

      respond_to do |format|
        format.html { redirect_to view_context.model_path }
        format.json { head :no_content }
      end
    end

    # GET /open_lists/:domain/:list_name/define
    def define_model
      respond_to do |format|
        format.html
        format.json { head :no_content }
      end
    end




    private

    def actual_list_param_name
      @model.name.underscore.tr '/', '_'
    end


  end
end

app/helpers/open_lists/application_helper.rb
module OpenLists
  module ApplicationHelper

    MAX_TO_BE_DISPLAYED_AS_CHECKBOXES = 10

    DIRECTIONS = {
        text: {
          desc: I18n.t('openlists.descending', :default => "descending"),
          asc:  I18n.t('openlists.ascending', :default => "ascending")
        },
        glyph: {
            desc: 'icon-chevron-down',
            asc: 'icon-chevron-up'
        }
    }

    def current_direction
      sort_direction
    end
    def other_direction
      sort_direction == 'desc' ? 'asc' : 'desc'
    end
    def display_current_direction() DIRECTIONS[:text][current_direction.to_sym] end
    def display_other_direction() DIRECTIONS[:text][other_direction.to_sym] end
    def current_direction_glyph() DIRECTIONS[:glyph][current_direction.to_sym] end
    def other_direction_glyph() DIRECTIONS[:glyph][other_direction.to_sym] end


    ## 
    # @return a (remote) link to invert the current direction of the sort set through the session context in the list display
    # @param [String] column: the name of the column to sort the list by
    # @param [String] title: An optional title for the link (if not provided, will be guessed from the column name)
    # @param [String] title: An optional css class for the generated link
    def sortable_link(column, title: nil, css_class: "")
      column = column.to_s
      title = column.titleize if title.nil?
      css_class += column == sort_column ? " current_sort #{current_direction}" : ""
      direction = column == sort_column ? other_direction : current_direction
      unless block_given?
        link_to title, params.merge(sort: column, direction: direction), class: css_class, remote: true, method: :get
      else
        link_to(params.merge(sort: column, direction: direction), class: css_class, remote: true, method: :get) do
          content = yield title
          content.html_safe
        end
      end
    end

    ## 
    # @return a (remote) bootstrap button to invert the current direction of the sort set through the session context in the list display
    # @param [String] column: the name of the column to sort the list by
    # @param [String] title: An optional title for the link (if not provided, will be guessed from the column name)
    # @param [String] title: An optional css class for the generated link
    def sortable_link_as_button(column, title: nil, css_class: 'btn btn-mini', glyph: nil, &block)
      if block_given?
        sortable_link(column, title: title, css_class: css_class, &block)
      elsif glyph
        sortable_link(column, title: title, css_class: css_class) do |title|
          "#{title}&nbsp;<i class=\"#{glyph}\"></i>"
        end
      else
        sortable_link column, title: title, css_class: css_class
      end
    end

    ##
    # @return a (remote) link to set the param[:per] value for the number of items displayed in a list
    # @param [Integer] value: number of item to display in a list
    # @param [String] css_class: an optional css class for the generated link
    def per_link(value = params[:per], css_class = "")
      value = Kaminari.config.default_per_page if value.nil? #
      link_to value.to_s, params.merge(per: value), class: css_class, remote: true, method: :get
    end

    ##
    # @return a (remote) bootstrap button to set the param[:per] value for the number of items displayed in a list
    # @param [Integer] value: number of item to display in a list
    # @param [String] css_class: an optional css class for the generated link
    def per_link_as_button(value = nil, css_class = 'btn btn-mini')
      per_link value, css_class
    end

    ##
    # @return piece of html corresponding to the selector for the number of items to display in a list
    # @param [Integer] value: number of item to display in a list
    def items_per_page_button_tag(value)
      render partial: 'items_per_page_button', locals: {value: value}
    end

    ##
    # @return piece of html corresponding to the header of the column in list display
    # @param [String] column
    # @param [Class] model
    def column_list_header_button_tag(column, model = @model)
      render partial: 'column_list_header_button', locals: {column: column, title: model.human_attribute_name(column)}
    end


    ##
    # @return a display name for the item. many options there.
    # It will take the best option:
    # * if the item itself knows how to be displayed (respond_to? :display_name_for_item), it will be the preferred choice
    # * if there is a non empty title column, it will use it.
    # * if there is a non empty name column, it will use it.
    # * if none of the above, it will display the name of class item is an instance of follow by the id number
    # * if there is no id (bad!!), it will display "No name"
    # @param [ActiveRecord::Base] item
    def display_name_for_item(item)
      return "" if item.nil?
      name = I18n.t('openlists.no_name', :default => "No name")
      if item.attribute_names.include? 'id'
        name = "#{item.class.name.titleize} ##{item.attributes['id']}"
        name = "#{item.class.display_name} ##{item.attributes['id']}" if item.class.respond_to? :display_name
      end
      name = item.attributes['name'] unless item.attributes['name'].blank?
      name = item.attributes['title'] unless item.attributes['title'].blank?
      name = item.class.display_name_for_item(item) if item.class.respond_to? :display_name_for_item
      name
    end

    def collections_linked_to(model = @model)
      model.reflections.keys.map do |column|
        column if model.reflections[column].collection?
      end .compact
    end


    ##
    # @return an array of editable attributes for this model
    # REVIEW: shouldn't primary key and timestamps be removed at this level ?
    # @param [Class] model
    def fields_to_edit_for_model(model = @model)
      model.attribute_names
    end


    ##
    # @return an of the fields to be displayed for this model
    # @param [Class] model
    def fields_to_display_for_model(model = @model)
      fields = model.attr_accessible[:default].to_a - [""]
      fields = model.attribute_names if fields.empty?
      # Special case it's a has_many relation
      fields.delete_if {|field| model.reflections.keys.include? field.gsub(/_ids$/, '').pluralize.to_sym }
      fields
    end

    def has_few_records?(domain, association_name)
      association_model = domain.model_class(association_name.to_s.pluralize)
      association_model.count < MAX_TO_BE_DISPLAYED_AS_CHECKBOXES
    end


    ##
    # @return the base url of the engine
    def module_base_url
      Engine.routes.default_scope[:module]
    end

  end
end

app/helpers/open_lists/domains_helper.rb
module OpenLists
  module DomainsHelper

    def domain_path(domain = @domain)
      path = (domain.class == String) ? domain : domain.prefix
      "/#{module_base_url}/#{path}"
    end

    def new_domain_path
      "/#{module_base_url}/new"
    end

    def domains_path(*args)
      "/#{module_base_url}"
    end

  end
end

app/helpers/open_lists/generic_helper.rb
# -*- coding: utf-8 -*-
module OpenLists
  module GenericHelper

    # @return the path for a new item
    def new_item_path
      return "/#{module_base_url}/#{params[:domain]}/#{params[:list_name]}/new" if params[:domain] and params[:list_name]
      "/#{module_base_url}/#{@domain.to_param}"
    end

    # @return the path to the list item passed (default is current)
    # @param [DynamicModel::ActiveRecordExtension] item
    def item_path(item = @item)
      return "#{model_path(item.class)}/#{item.to_param}" unless item.nil?
      "/#{module_base_url}/#{params[:domain]}/#{params[:list_name]}/#{params[:id]}" if params[:domain] and params[:list_name] and params[:id]
    end

    # @return the path to the list index passed (default is current)
    # @param [Class] model
    def model_path(model = @model)
      "/#{module_base_url}/#{model.to_param}"
    end

    # @return the edit path to the list item passed (default is current)
    # @param [DynamicModel::ActiveRecordExtension] item
    def edit_item_path(item = @item)
      "#{item_path item}/edit"
    end


    # @return provides an option hash for the form tag as the controller is very specific
    # @param [DynamicModel::ActiveRecordExtension] item
    def form_options(item = @item)
      {url: item_path(item), controller: 'OpenLists::Generic'}
    end

    ## 
    # @return the html to display the attribute of the item
    # @param [ActiveRecord::Base] item
    # @param [String] attribute
    def field_as_display_element(item, attribute)
      attribute_type = item.class.columns_hash[attribute].type
      case attribute_type
        when :integer
          # Special case: is it a link to another table
          if item.class.reflections.keys.include? attribute.gsub(DynamicModel::RelationsAnalyser::KEY_IDENTIFIER, '').to_sym
            child = item.send attribute.gsub(DynamicModel::RelationsAnalyser::KEY_IDENTIFIER, '').to_sym
            return link_to(display_name_for_item(child), item_path(child))
          end
          # Else just show the number
          item.attributes[attribute]
        when :boolean
          check_box_tag attribute, "", item.attributes[attribute], disabled: true
        else
          h item.attributes[attribute]
      end
    end

    ## 
    # @return the html to edit the attribute of the item
    # @param [ActionView::Helpers::FormBuilder] form
    # @param [Class] model (descendant of ActiveRecord::Base)
    # @param [String] attribute
    def field_as_edit_element(form, model, attribute)
      attribute_type =  model.columns_hash[attribute].type
      case attribute_type
        when :integer
          # Is it the primary key ?
          return form.text_field(attribute.to_sym, disabled: true) if attribute == model.primary_key
          # Special case: is it a link to another table?
          # if it is, then it should end with DynamicModel::RelationsAnalyser::KEY_IDENTIFIER
          reflection_key = attribute.gsub(DynamicModel::RelationsAnalyser::KEY_IDENTIFIER, '').to_sym
          if model.reflections.keys.include? reflection_key
            content = model.reflections[reflection_key].class_name.constantize.all.map do |s|
              [ display_name_for_item(s), s[s.class.primary_key] ]
            end
            return form.select(attribute, content, {include_blank: I18n.t('openlists.none', default: 'None')})
          end
          # Else just show the number
          form.number_field attribute.to_sym
        when :boolean
          form.check_box attribute.to_sym
        when :datetime
          if ['created_at', 'updated_at'].include? attribute
            form.text_field attribute.to_sym, disabled: true
          else
            form.text_field attribute.to_sym, class: "date-picker-field"
          end
        else
          form.text_field attribute.to_sym
      end
    end

  end
end

app/views/open_lists/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
    <% if @domain.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

          <ul>
            <% @domain.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!-- Display Standard fields and belongs_to associations-->
    <% fields_to_edit_for_model(@model).each do |field| %>
        <div class="fields">
          <%= render partial: 'form_field', locals: {model: @model, domain: @domain, field: field, f: f} %>
        </div>
    <% end %>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/open_lists/domains/_list.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<% if @domains.empty? %>
    <%= content_tag :div, t("openlists.empty_domain_list", default: "There is no domain defined."), class: "well well-large" %>
<% else %>

    <% column_list_to_display = ['name', 'description'] %>
    <div class="row-fluid">
      <div class="span12">
        <div class="accordion" id="domain-accordion">
          <% @domains.each do |domain| %>
              <%= content_tag :div, class: 'accordion-group' do %>
                  <%= content_tag :div, class: 'accordion-heading' do %>
                      <%= link_to domain.name, "#domain_#{domain.id}", data: {toggle: 'collapse', parent: '#domain-accordion'} %>
                  <% end %>
                  <%
                    accordion_body_class = %w(accordion-body collapse)
                    accordion_body_class << 'in' if params[:domain] == domain.name
                  %>
                  <%= content_tag :div, class: accordion_body_class.join(" "), id: "domain_#{domain.id}" do %>
                      <%= content_tag :div, class: 'accordion-inner' do %>
                          <%= render :partial => 'show', locals: {domain: domain} %>
                      <% end %>
                  <% end %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/open_lists/domains/_show.html.erb
<%= content_tag :div, id: 'domain', data: {object: domain.inspect} do %>
    <%= content_tag :div, class: 'row-fluid' do %>
        <%= content_tag :div, class: 'librairy-lists span6' do %>
            <%= t('openlists.description', default: "Lists in that library") %>:
            <% unless domain.empty? %>
                <ul class="nav nav-pills nav-stacked">
                  <% domain.model_classes.each do |model| %>
                      <%= content_tag :li do %>
                          <%= link_to(model.display_name.pluralize, model_path(model)) %>
                      <% end %>
                  <% end %>
                </ul>
            <% end %>
        <% end %>
        <%= content_tag :div, class: 'details span6' do %>
            <%= t('openlists.description', default: "Description") %>:
            <%= content_tag :div, domain.description , class: "well well-large" %>
        <% end %>
    <% end %>
    <%= content_tag :div, class: 'row-fluid' do %>
        <%= t('openlists.created_at', default: "Created on") %>:
        <%= domain.created_at %>
        <%= t('openlists.updated_at', default: "Updated on") %>:
        <%= domain.updated_at %>
    <% end %>
<% end %>

app/views/open_lists/domains/edit.html.erb
<h1><%= t('openlists.edit_domain', default: "Modifying a domain") %></h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/open_lists/domains/index.html.erb
<div class="page-header row-fluid">
  <h1><%= t nil, default: t('openlists.list_of', default: "List of %s") % [t('openlists.libraries', default: 'Libraries')] %></h1>
</div>

<div class="row-fluid" id="items-list">
  <%= render :partial => 'list' %>
</div>

<div class="row-fluid">
  <%= link_to t('openlists.import_domain', default: "Import a domain"),
              new_domain_path,
              :class => 'btn btn-mini btn-primary' %>
</div>

app/views/open_lists/domains/new.html.erb
<h1><%= t('openlists.import_domain', default: "Import a domain") %></h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/open_lists/domains/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>